import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Navbar from "@/app/components/Navbar";
import Providers from "./Providers";
import { ApolloWrapper } from "./ApolloWrapper";
import { UserProvider } from "@auth0/nextjs-auth0/client";
import Auth0Wrapper from "./Auth0Wrapper";
const inter = Inter({ subsets: ["latin"] });
inter.className;
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="h-full">
      <body className="bg-background-primary text-white min-h-full">
        {/* <UserProvider> */}
        <Auth0Wrapper>
          <ApolloWrapper>
            <Providers>
              <Navbar />
              {children}
            </Providers>
          </ApolloWrapper>
        </Auth0Wrapper>
        {/* </UserProvider> */}
      </body>
    </html>
  );
}
